export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function ApiLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div data-testid="api-layout">{children}</div>
      </body>
    </html>
  );
}
