import { Container } from '@mui/material';

import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Container sx={{ maxWidth: '1440px', height: '100%' }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
