import { Container } from '@mui/material';
import type { Metadata } from 'next';

import './globals.css';

import { i18n, type Locale } from '@/i18n-config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body>
        <Container sx={{ maxWidth: '1440px' }}>{children}</Container>
      </body>
    </html>
  );
}
